# Trying some prediction

In [135]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LogisticRegression

In [17]:
#purple_cap_df=pd.read_csv("purple_cap.csv")
matches=pd.read_csv("matches.csv")
purple_cap=pd.read_csv("purple_cap.csv")
orange_cap=pd.read_csv("orange_cap.csv")

In [7]:
matches_df.isna().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             1
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       2
second_ings_wkts        2
match_result            0
match_winner            3
wb_runs                40
wb_wickets             36
balls_left              2
player_of_the_match     3
top_scorer              3
highscore               3
best_bowling            3
best_bowling_figure     3
dtype: int64

In [9]:
orange_cap_df.isna().sum()

Position         0
Batsman          0
Team             0
Matches          0
Innings          0
Not_out          0
Runs             0
Highest_score    0
Average          0
Balls_faced      0
Strike_rate      0
Hundreds         0
Fifties          0
Ducks            0
Fours            0
Sixes            0
dtype: int64

In [103]:
matches_df.isna().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       2
second_ings_wkts        2
match_result            0
match_winner            0
wb_runs                40
wb_wickets             36
balls_left              2
player_of_the_match     3
top_scorer              3
highscore               3
best_bowling            3
best_bowling_figure     3
dtype: int64

In [105]:
matches_df['wb_runs'] = pd.to_numeric(matches_df['wb_runs'], errors='coerce')
matches_df['wb_wickets'] = pd.to_numeric(matches_df['wb_wickets'], errors='coerce')

In [107]:
num_cols = ['first_ings_score', 'first_ings_wkts', 'second_ings_score', 'second_ings_wkts',
            'balls_left', 'highscore', 'wb_runs', 'wb_wickets']
for col in num_cols:
    matches_df[col].fillna(matches_df[col].mean(), inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_11248\597643492.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_df[col].fillna(matches_df[col].mean(), inplace=True)

In [109]:
cat_cols = ['toss_winner', 'match_winner', 'player_of_the_match', 
            'top_scorer', 'best_bowling', 'best_bowling_figure']
for col in cat_cols:
    matches_df[col].fillna(matches_df[col].mode()[0], inplace=True)

C:\Users\ACER\AppData\Local\Temp\ipykernel_11248\2729782307.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_df[col].fillna(matches_df[col].mode()[0], inplace=True)
C:\Users\ACER\AppData\Local\Temp\ipykernel_11248\2729782307.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  matches_df[col].fillna(matches_df[col].mode()[0], inplace=True)

In [111]:
matches_df.isna().sum()

match_id               0
date                   0
venue                  0
team1                  0
team2                  0
stage                  0
toss_winner            0
toss_decision          0
first_ings_score       0
first_ings_wkts        0
second_ings_score      0
second_ings_wkts       0
match_result           0
match_winner           0
wb_runs                0
wb_wickets             0
balls_left             0
player_of_the_match    0
top_scorer             0
highscore              0
best_bowling           0
best_bowling_figure    0
dtype: int64

In [113]:
matches_df['match_winner'].unique()

array([ 7,  9,  0,  1,  6,  3,  4,  2,  8,  5, 10], dtype=int64)

In [117]:
matches_df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_result,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 22,2025",3,3,7,1,7,1,174.0,8.0,...,completed,7,33.181818,7.000000,22.0,Krunal Pandya,Virat Kohli,59.0,Krunal Pandya,3--29
1,2,"March 23,2025",10,9,8,1,8,1,286.0,6.0,...,completed,9,44.000000,6.324324,0.0,Ishan Kishan,Ishan Kishan,106.0,Tushar Deshpande,3--44
2,3,"March 23,2025",7,0,5,1,0,1,155.0,9.0,...,completed,0,33.181818,4.000000,5.0,Noor Ahmad,Rachin Ravindra,65.0,Noor Ahmad,4--18
3,4,"March 24,2025",0,1,4,1,1,1,209.0,8.0,...,completed,1,33.181818,1.000000,3.0,Ashutosh Sharma,Nicholas Pooran,75.0,Mitchell Starc,3--42
4,5,"March 25,2025",8,2,6,1,2,1,243.0,5.0,...,completed,6,11.000000,6.324324,0.0,Shreyas Iyer,Shreyas Iyer,97.0,Sai Kishore,3--30

In [119]:
from sklearn.preprocessing import LabelEncoder

# Columns with categorical string values
cat_cols = ['venue', 'team1', 'team2', 'stage', 'toss_winner', 'toss_decision', 'match_winner']

le = LabelEncoder()

# Encode each column in-place
for col in cat_cols:
    matches_df[col] = le.fit_transform(matches_df[col])

In [123]:
df = matches_df[['venue', 'team1', 'team2', 'stage', 'toss_winner', 'toss_decision',
              'first_ings_score', 'first_ings_wkts','match_winner']]
df.head()

,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,match_winner
0,3,3,7,1,7,1,174.0,8.0,7
1,10,9,8,1,8,1,286.0,6.0,9
2,7,0,5,1,0,1,155.0,9.0,0
3,0,1,4,1,1,1,209.0,8.0,1
4,8,2,6,1,2,1,243.0,5.0,6

In [137]:
X = df.drop(columns=['match_winner'])
y = df['match_winner']

In [139]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [141]:
model = LogisticRegression()
model.fit(X_train, y_train)

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [143]:
y_pred = model.predict(X_test)

In [145]:
print("accuracy_score :", accuracy_score(y_test, y_pred))
print("classification_report:\n",  classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

accuracy_score : 0.0
classification_report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       4.0
           2       0.00      0.00      0.00       3.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       1.0
           5       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       2.0
           7       0.00      0.00      0.00       3.0
           8       0.00      0.00      0.00       1.0
           9       0.00      0.00      0.00       0.0

    accuracy                           0.00      15.0
   macro avg       0.00      0.00      0.00      15.0
weighted avg       0.00      0.00      0.00      15.0

confusion_matrix:
 [[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 2 0 0 0 0 0 1]
 [1 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 1]
 [0 0 0 2 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [29]:
y_pred = model.predict(X_test)

In [31]:
print("accuracy_score :", accuracy_score(y_test, y_pred))
print("classification_report:\n",  classification_report(y_test, y_pred))
print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))

accuracy_score : 0.6666666666666666
classification_report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

confusion_matrix:
 [[1 0]
 [1 1]]

In [33]:
X = orange_cap[['Matches', 'Innings', 'Balls_faced','Fifties','Ducks','Fours', 'Sixes']]
y = orange_cap['Runs']

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
from sklearn.neural_network import MLPRegressor

mlp_model = MLPRegressor(hidden_layer_sizes=(100,50), max_iter=500, random_state=42)
mlp_model.fit(X_train, y_train)

MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42)

In [39]:
y_pred = mlp_model.predict(X_test)

In [45]:
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:",mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.8336597941812607
MAE: 37.04014531974915
MSE: 2318.1540727801334
RMSE: 48.14721251308463

In [81]:
from xgboost import XGBRegressor

In [47]:
purple_cap['Economy_per_Over'] = purple_cap['Runs'] / purple_cap['Overs']
purple_cap['Balls_per_Wicket'] = purple_cap['Balls'] / purple_cap['Wickets'].replace(0, 1)
purple_cap['Wickets_per_Match'] = purple_cap['Wickets'] / purple_cap['Matches']

In [49]:
features = ['Matches', 'Innings', 'Balls', 'Overs', 'Runs', 
            'Economy_per_Over', 'Balls_per_Wicket', 'Wickets_per_Match']

X = purple_cap[features]
y = purple_cap['Wickets']

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [83]:
xgb_model =XGBRegressor()
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [85]:
y_pred = xgb_model.predict(X_test)

In [87]:
print("R2 Score:", r2_score(y_test, y_pred))
print("MAE:",mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.47383707761764526
MAE: 1.9868907928466797
MSE: 8.535531735643113
RMSE: 2.9215632349211806